export const typeMappings = {
  python: {
    "int": "int",
    "float": "float",
    "bool": "bool",
    "char": "str",
    "string": "str",
    "void": "None",
    "int[]": "List[int]",
    "float[]": "List[float]",
    "bool[]": "List[bool]",
    "char[]": "List[str]",
    "string[]": "List[str]",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  },
  java: {
    "int": "int",
    "long": "long",
    "float": "float",
    "double": "double",
    "bool": "boolean",
    "char": "char",
    "string": "String",
    "void": "void",
    "int[]": "int[]",
    "long[]": "long[]",
    "float[]": "float[]",
    "double[]": "double[]",
    "bool[]": "boolean[]",
    "char[]": "char[]",
    "string[]": "String[]",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  },
  cpp: {
    "int": "int",
    "long": "long",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "char": "char",
    "string": "std::string",
    "void": "void",
    "int[]": "std::vector<int>",
    "long[]": "std::vector<long>",
    "float[]": "std::vector<float>",
    "double[]": "std::vector<double>",
    "bool[]": "std::vector<bool>",
    "char[]": "std::vector<char>",
    "string[]": "std::vector<std::string>",
    "ListNode": "ListNode*",
    "TreeNode": "TreeNode*",
    "GraphNode": "GraphNode*"
  },
  typescript: {
    "int": "number",
    "long": "number",
    "float": "number",
    "double": "number",
    "bool": "boolean",
    "char": "string",
    "string": "string",
    "void": "void",
    "int[]": "number[]",
    "long[]": "number[]",
    "float[]": "number[]",
    "double[]": "number[]",
    "bool[]": "boolean[]",
    "char[]": "string[]",
    "string[]": "string[]",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  },
  ruby: {
    "int": "",
    "float": "",
    "bool": "",
    "char": "",
    "string": "",
    "void": "",
    "int[]": "",
    "float[]": "",
    "bool[]": "",
    "char[]": "",
    "string[]": "",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  },
  go: {
    "int": "int",
    "long": "int64",
    "float": "float64",
    "double": "float64",
    "bool": "bool",
    "char": "byte",
    "string": "string",
    "void": "",
    "int[]": "[]int",
    "long[]": "[]int64",
    "float[]": "[]float64",
    "double[]": "[]float64",
    "bool[]": "[]bool",
    "char[]": "[]byte",
    "string[]": "[]string",
    "ListNode": "*ListNode",
    "TreeNode": "*TreeNode",
    "GraphNode": "*GraphNode"
  },
  rust: {
    "int": "i32",
    "long": "i64",
    "float": "f32",
    "double": "f64",
    "bool": "bool",
    "char": "char",
    "string": "String",
    "void": "()",
    "int[]": "Vec<i32>",
    "long[]": "Vec<i64>",
    "float[]": "Vec<f32>",
    "double[]": "Vec<f64>",
    "bool[]": "Vec<bool>",
    "char[]": "Vec<char>",
    "string[]": "Vec<String>",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  },
  ocaml: {
    "int": "int",
    "long": "int64",
    "float": "float",
    "double": "float",
    "bool": "bool",
    "char": "char",
    "string": "string",
    "void": "unit",
    "int[]": "int list",
    "long[]": "int64 list",
    "float[]": "float list",
    "double[]": "float list",
    "bool[]": "bool list",
    "char[]": "char list",
    "string[]": "string list",
    "ListNode": "listNode",
    "TreeNode": "treeNode",
    "GraphNode": "graphNode"
  },
  csharp: {
    "int": "int",
    "long": "long",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "char": "char",
    "string": "string",
    "void": "void",
    "int[]": "List<int>",
    "long[]": "List<long>",
    "float[]": "List<float>",
    "double[]": "List<double>",
    "bool[]": "List<bool>",
    "char[]": "List<char>",
    "string[]": "List<string>",
    "ListNode": "ListNode",
    "TreeNode": "TreeNode",
    "GraphNode": "GraphNode"
  }
};
